{"name": "test_admin_product_json_add", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data.json'", "trace": "self = <src.ayan_api.core_api.Test_admin_product_controller object at 0x0000022F61C9A0A0>\ntest_authorization = 'BearereyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkdWNhdC1zcHJpbmdib290LWp3dHRva2VuIiwicG93ZXJzIjoiYWRtaW5fYWRkcmVzc193YXRjaCxhZG...joiMjAyNC0wNS0wMSAxOTo0NjozOCJ9.5S2_oIWaj0sLYRtBqXBtStepn0ZBAi4FeZ7Jf-Ye0g3vAgrAwEYf5OxEsKXikRbA_UxZto_dR6esl2Yda6RStA'\n\n    def test_admin_product_json_add(self, test_authorization):\n        url = global_url + \"/api/admin/product/json/add\"\n        headers = {\"Content-Type\": \"application/json\", \"token\": f'{test_authorization}'}\n        filename = \"../data.json\"\n>       with open(filename, \"rb\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data.json'\n\nsrc\\ayan_api\\core_api.py:13: FileNotFoundError"}, "start": 1682970399485, "stop": 1682970399485, "uuid": "f4fe4f35-f8c1-42ae-b99b-b490c5f10aa9", "historyId": "726570cb57959fb90028b0e06e2e659b", "testCaseId": "726570cb57959fb90028b0e06e2e659b", "fullName": "tests.test_admin_product_controller.Test_Produts#test_admin_product_json_add", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_admin_product_controller"}, {"name": "subSuite", "value": "Test_Produts"}, {"name": "host", "value": "DESKTOP-7AMLUJI"}, {"name": "thread", "value": "29088-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_admin_product_controller"}]}